### ISSUE TITLE
Compiling Lede 17.04.1

### ISSUE THREAD

**Issue by openwr** [pgid69/bcm63xx-phone#20]
Hello, I am trying now to compile your driver with Lede 17.01.4. I cannot understand the modiffy I need to do for spi. With no modify, when I start module I have

[  261.983861] bcm63xx_phone phone_dev_le88221_init() 56: phone_dev_le88221_init()
[  261.991439] bcm63xx_phone phone_dev_zarlink_ve880_init() 2017: phone_dev_zarlink_ve880_init()
[  262.000269] bcm63xx_phone bcm_mpi_init() 878: bcm_mpi_init()
 **[  262.006147] bcm63xx_phone: Error: Driver 'bcm63xx-spi' is already registered, aborting...**
[  262.014633] bcm63xx_phone bcm_periodic_work_deinit() 103: bcm_periodic_work_deinit()
[  262.022650] bcm63xx_phone bcm_period_deinit() 33: bcm_period_deinit()
[  262.029332] bcm63xx_phone bcm63xx_phone_init() 1207: Freeing mmap buffer used for RX, TX...
[  262.037992] bcm63xx_phone bcm_periodic_timer_deinit() 265: bcm_periodic_timer_deinit()
[  262.046189] bcm63xx_phone bcm_timer_stop() 167: bcm_timer_stop()

Cna you please explain which patch I need when I compile Lede?

**Comment by pgid69** [comment]
Hello
slic device le88221 is connected to the spi bus.
But actual spi driver in linux kernel is inefficient because it doesn't allow toggling CS signal between each byte. So transfer are very slow
That's why i integrate spi module in bcm63xx-phone kernel module and modified the code to allow very fast transfer.
But of course it conflicts with linux kernel spi module
That's why you have to disable the spi module in the linux kernel and recompile it.
Either you apply the patch 000-disable-spi-bcm63xx-module.patch in bcm63xx-phone/patches/17.01.
Or you run make kernel_menuconfig and disable the spi driver.
