### ISSUE TITLE
HG655b voip (LE89116)

### ISSUE THREAD

**Issue by Team-Proton** [pgid69/bcm63xx-phone#21]
can we add LE89116 support to HG655b/d ?
B.R

**Comment by pgid69** [comment]
Hello

Without the router for testing, i can't.

Because the SoC is a BCM6368 and not a BCM6358. 

I see several difficulties :
- the code for initializing the PLL which delivers clock for the PCM bus is different and i never test it.
- the GPIO for enabling the SPI slaves are different and once again i never test the code.
- with BCM6368 there's a new driver for handling SPI bus, the HSSPI driver, and i don't know if it replaces the SPI driver or it is an alternate driver.

BR
